# Generated by Django 5.0.1 on 2024-03-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_profile_email_profile_renter_or_client"),
        ("renters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
        migrations.AddField(
            model_name="item",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.profile",
            ),
            preserve_default=False,
        ),
    ]
