# Generated by Django 5.0.1 on 2024-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="renter_or_client",
            field=models.CharField(
                choices=[("R", "Renter"), ("C", "Client")], default=1, max_length=2
            ),
            preserve_default=False,
        ),
    ]
