# Generated by Django 5.0.3 on 2024-04-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_profile_email_profile_renter_or_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="CnfOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("ship_to_different_address", models.BooleanField(default=False)),
                ("order_notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.profile"
                    ),
                ),
            ],
        ),
    ]
